sudo: required

env: SWIFT_VERSION=5.0.1

matrix:
  include:
    - os: osx
      compiler: clang
      osx_image: xcode10.2
      env:
      stage: main-test
    - os: linux
      dist: xenial
      compiler: clang
      install:
        - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"

script:
  - swift test