sudo: required

env: SWIFT_VERSION=5.0.1

matrix:
  include:
    - os: osx
      osx_image: xcode10.2
      stage: main-test
      language: Swift
    - os: linux
      dist: xenial
      install:
        - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
      language: Swift

script:
  - swift test